version: '3.7'
services:
  angular_tc_build:
    container_name: angularjs_app
    build:
      context: .
      dockerfile: DockerfileMultiStage
      target: BUILD_STAGE
  angular_tc_deploy:
    container_name: angularjs_app
    build:
      context: .
      dockerfile: DockerfileMultiStage
    ports:
      - 8080:8080
    environment:
      SERVICE1_API_URL: http://zuul_deploy:8081/svc1
      SERVICE2_API_URL: http://zuul_deploy:8081/svc2
      LOCAL_DEV: 'true'
networks:
  default:
    external:
      name: comet-network
