version: '3.7'
services:
  app_build:
    container_name: angularjs_app
    build:
      context: .
      dockerfile: DockerfileMultiStage
      target: BUILD_STAGE
  app_deploy:
    container_name: angularjs_app
    build:
      context: .
      dockerfile: DockerfileMultiStage
    ports:
      - 8080:8080
    environment:
      API_URL: http://localhost:4000
      LOCAL_DEV: 'true'
