apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    author: Levon Becker
  labels:
    comet.app: angularjs
  name: angularjs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 150%
  selector:
    matchLabels:
      comet.app: angularjs
  template:
    metadata:
      labels:
        app: angularjs
      namespace: comet
    spec:
      containers:
      - env:
        - name: LOCAL_DEV
          value: "true"
        - name: SERVICE1_API_URL
          value: http://comet_zuul:8081/svc1
        - name: SERVICE2_API_URL
          value: http://comet_zuul:8081/svc2
        image: comet_angularjs_deploy
        name: angularjs
        ports:
        - containerPort: 8080
        resources: {}
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
