apiVersion: v1
kind: Service
metadata:
  annotations:
    author: Levon Becker
  labels:
    comet.service: angularjs
  name: angularjs
  namespace: comet
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    comet.service: angularjs
  type: LoadBalancer
