apiVersion: v1
kind: Service
metadata:
  annotations:
    author: Levon Becker
  labels:
    comet.service: angularjs
  name: angularjs
  namespace: comet
spec:
  ports:
    - name: "service-port"
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    comet.app: angularjs
  type: LoadBalancer
